version: '3'

services:
  jiraDB:
    build: ./psql-docker
    image: jiradb
    networks:
      - jira-network
    tty: true
    entrypoint:
      - /usr/lib/postgresql/9.6/bin/postgres
      - -D
      - /var/lib/postgresql/9.6/main
      - -c
      - "config_file=/etc/postgresql/9.6/main/postgresql.conf"
      - -c
      - "listen_addresses=*"
  jiraUI:
    build: ./jira-docker
    image: jiraui
    networks:
      - jira-network
    depends_on:
      - jiraDB
    volumes:
      - "var_jira:/var/atlassian/jira"
      - "opt_jira:/opt/atlassian/jira"
    ports:
      - "8888:8080"
    tty: true

networks:
  jira-network:

volumes:
  var_jira:
  opt_jira:
